# Generated by Django 3.2.9 on 2021-11-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordentry',
            name='description',
        ),
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('word_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meanings', to='dictionary.wordentry')),
            ],
            options={
                'verbose_name': 'Word meaning',
                'verbose_name_plural': 'Word meanings',
                'ordering': ['id'],
            },
        ),
    ]
