# Generated by Django 3.2.9 on 2021-11-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20211105_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proverb',
                'verbose_name_plural': 'Proverbs',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='WordMeaning',
            new_name='Meaning',
        ),
        migrations.AlterModelOptions(
            name='meaning',
            options={'ordering': ['id'], 'verbose_name': 'Meaning', 'verbose_name_plural': 'Meanings'},
        ),
    ]
